### ISSUE TITLE
Blizzard: Overwatch stats not working without any competitive played.

### ISSUE THREAD

**Issue by Naichoryss** [flapjax/FlapJack-Cogs#16] opened 2017-03-26 10:25 UTC
When requesting the Overwatch stats for my account (Naichoryss#1808) I get the following error:

> ERROR red on_command_error 364: Exception in command 'overwatch stats'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "botdir\cogs\blizzard.py", line 190, in _stats_overwatch
    thumb_url = comp['overall_stats']['avatar']
TypeError: 'NoneType' object is not subscriptable

Obviously I've never played competitive.

**Comment by HelmicNewciv** [comment] 2017-03-26 10:30
If you haven't played any competitive this season, it will also fetch stats from the last season you did play comp in; this is obviously confusing because no mention is made of this, so people were wondering how the fuck I already have 206 comp wins in season 4.

**Comment by flapjax** [comment] 2017-03-27 02:11
Both issues acknowledged. @Naichoryss, your issue is probably because the battletag you checked has never played a competitive match. @HelmicNewciv, as you identified, the 3rd party API I am using probably pulls the previous season competitive stats if you haven't played this season. I will address both issues when I overhaul this cog.

**Comment by Naichoryss** [comment] 2017-03-31 10:36
I'm not a programmer, so I probably made a few formatting mistakes, and there's probably a better way to do this.
But here's what I changed to get it working for me. Just a few If Else.

````
    @overwatch.command(name="stats", pass_context=True)
    async def _stats_overwatch(self, ctx, tag: str=None, region: str=None):
        """Overwatch stats for your battletag (case sensitive and PC only!).
        If battletag is ommitted, bot will use your battletag if stored.
        Region is optional and will autodetect with this priority: kr>eu>us

        Example: [p]overwatch stats CoolDude#1234 kr
        """

        uid = ctx.message.author.id
        # Little hack to detect if region was entered, but not battletag
        if (tag in ['kr', 'eu', 'us']) and (region is None):
            region = tag
            tag = None

        if tag is None:
            if uid in self.settings['battletags']:
                tag = self.settings['battletags'][uid]
            else:
                await self.bot.say('You did not provide a battletag '
                                   'and I do not have one stored for you.')
                return

        tag = tag.replace("#", "-")
        url = 'https://owapi.net/api/v3/u/' + tag + '/stats'
        async with aiohttp.ClientSession(headers=self.header) as session:
            async with session.get(url) as resp:
                stats = await resp.json()

        if 'error' in stats:
            await self.bot.say('Could not fetch your statistics. '
                               'Battletags are case sensitive '
                               'and require a 4 or 5-digit identifier '
                               '(e.g. CoolDude#1234)'
                               'Or, you may have an invalid tag '
                               'on file.')
            return

        if region is None:
            if stats['kr']:
                region = 'kr'
                region_full = 'Asia'
            elif stats['eu']:
                region = 'eu'
                region_full = 'Europe'
            elif stats['us']:
                region = 'us'
                region_full = 'US'
            else:
                await self.bot.say('That battletag has no stats in any region.')
                return

        if stats[region] is None:
            await self.bot.say('That battletag exists, but I could not '
                               'find stats for the region specified. '
                               'Try a different region '
                               '<us/eu/kr> or leave that field blank '
                               'so I can autodetect the region.')
            return

        url = 'https://playoverwatch.com/en-us/career/pc/' + region + '/' + tag
        tag = tag.replace("-", "#")
        comp = stats[region]['stats']['competitive']
        qplay = stats[region]['stats']['quickplay']
        if comp == None:		
            thumb_url = qplay['overall_stats']['avatar']
        else:		
            thumb_url = comp['overall_stats']['avatar']
		
        if comp == None:		
            icon_url = 'http://i.imgur.com/xU2iv6U.png'
        else:
            tier = comp['overall_stats']['tier']
            if tier == 'bronze':
                icon_url = 'http://i.imgur.com/B4IR72H.png'
            elif tier == 'silver':
                icon_url = 'http://i.imgur.com/1mOpjRc.png'
            elif tier == 'gold':
                icon_url = 'http://i.imgur.com/lCTsNwo.png'
            elif tier == 'platinum':
                icon_url = 'http://i.imgur.com/nDVHAbp.png'
            elif tier == 'diamond':
                icon_url = 'http://i.imgur.com/fLmIC70.png'
            elif tier == 'master':
                icon_url = 'http://i.imgur.com/wjf0lEc.png'
            elif tier == 'grandmaster':
                icon_url = 'http://i.imgur.com/5ApGiZs.png'
            else:
                icon_url = 'http://i.imgur.com/xU2iv6U.png'

        if comp == None:
            qplay_stats = ''.join(['**Wins:** ', str(int(round(qplay['game_stats']['games_won']))),
								   '\n**Avg Elim:** ', str(int(round(qplay['average_stats']['eliminations_avg']))),
								   '\n**Avg Death:** ', str(int(round(qplay['average_stats']['deaths_avg']))),
								   '\n**Avg Dmg:** ', str(int(round(qplay['average_stats']['damage_done_avg']))),
								   '\n**Avg Heal:** ', str(int(round(qplay['average_stats']['healing_done_avg'])))])
        else:
            comp_stats = ''.join(['**Wins:** ', str(int(round(comp['game_stats']['games_won']))),
								  '\n**Avg Elim:** ', str(int(round(comp['average_stats']['eliminations_avg']))),
								  '\n**Avg Death:** ', str(int(round(comp['average_stats']['deaths_avg']))),
								  '\n**Avg Dmg:** ', str(int(round(comp['average_stats']['damage_done_avg']))),
								  '\n**Avg Heal:** ', str(int(round(comp['average_stats']['healing_done_avg'])))])

            qplay_stats = ''.join(['**Wins:** ', str(int(round(qplay['game_stats']['games_won']))),
								   '\n**Avg Elim:** ', str(int(round(qplay['average_stats']['eliminations_avg']))),
								   '\n**Avg Death:** ', str(int(round(qplay['average_stats']['deaths_avg']))),
								   '\n**Avg Dmg:** ', str(int(round(qplay['average_stats']['damage_done_avg']))),
								   '\n**Avg Heal:** ', str(int(round(qplay['average_stats']['healing_done_avg'])))])

							   
        embed = discord.Embed(title='Overwatch Stats (PC-' + region_full + ')', color=0xFAA02E)
        embed.set_author(name=tag, url=url, icon_url=icon_url)
        embed.set_thumbnail(url=thumb_url)
        if comp == None:
            embed.add_field(name='__Quick Play__', value=qplay_stats, inline=True)
        else:		
            embed.add_field(name='__Competitive__', value=comp_stats, inline=True)
            embed.add_field(name='__Quick Play__', value=qplay_stats, inline=True)
        await self.bot.say(embed=embed)

````

**Comment by flapjax** [comment] 2017-03-31 15:18
Thanks so much for sharing. This is on the right track. The API gives a null value for competitive stats if no games are played. I'm working on this issue tonight, and I will use a similar method.

On a related note, does anybody have a confirmed example of a profile that has *still* not played in the current competitive season, but *did* play in the past one? That problem is proving a little more difficult to solve because I'm not seeing a season number in the API response.

**Comment by Naichoryss** [comment] 2017-03-31 16:31
As for someone who did play a previous season (don't know which) but not current season have a look at Ratman#2844
As far as I know he's not playing anymore.

**Comment by flapjax** [comment] 2017-03-31 23:26
This issue should be fixed with the latest update 👌 . The stats embed will now show that you haven't played any competitive games.

**Closed by flapjax** 2017-03-31 23:26 UTC
Labels: Acknowledged
